version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(levelname)s - %(message)s'
        datefmt: '%d-%m-%Y %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
        
loggers:
    app:
        handlers: [console]
